steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/new-project-12133/flask-app:latest', '.']

  # Step 2: Push the image to the Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/new-project-12133/flask-app:latest']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/new-project-12133/flask-app:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/new-project-12133/flask-app:latest'

